name:                bulletproofs
version:             1.1.0
github:              "adjoint-io/bulletproofs"
license:             Apache
synopsis:            Bulletproofs are short zero-knowledge proofs without a trusted setup.
description:         Bulletproofs are short zero-knowledge arguments of knowledge that do not require a trusted setup.
maintainer:          Adjoint Inc (info@adjoint.io)
category:            Cryptography
extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >= 4.7 && < 5
- protolude >= 0.2
- text
- bytestring
- memory
- arithmoi >= 0.8
- containers
- MonadRandom
- QuickCheck
- galois-field >= 1 && < 2
- elliptic-curve >= 0.3 && < 0.4
- SHA

default-extensions:
  - LambdaCase
  - RecordWildCards
  - OverloadedStrings
  - NoImplicitPrelude
  - FlexibleInstances
  - ExplicitForAll
  - TypeApplications
  - ScopedTypeVariables
  - DeriveGeneric
  - BangPatterns
  - FlexibleContexts

ghc-options:
  -Wall
  -Wcompat
  -Wincomplete-record-updates
  -Wredundant-constraints
  -Wno-unused-matches
  -Wno-name-shadowing
  -Wno-type-defaults
  -Wno-orphans
  -Wno-incomplete-uni-patterns
  -Wno-incomplete-patterns

library:
  source-dirs: .
  exposed-modules:
    - Bulletproofs.RangeProof
    - Bulletproofs.RangeProof.Internal
    - Bulletproofs.RangeProof.Prover
    - Bulletproofs.RangeProof.Verifier

    - Bulletproofs.MultiRangeProof
    - Bulletproofs.MultiRangeProof.Prover
    - Bulletproofs.MultiRangeProof.Verifier

    - Bulletproofs.InnerProductProof
    - Bulletproofs.InnerProductProof.Internal
    - Bulletproofs.InnerProductProof.Prover
    - Bulletproofs.InnerProductProof.Verifier

    - Bulletproofs.ArithmeticCircuit
    - Bulletproofs.ArithmeticCircuit.Internal
    - Bulletproofs.ArithmeticCircuit.Prover
    - Bulletproofs.ArithmeticCircuit.Verifier

    - Bulletproofs.Utils

tests:
  bulletproofs-test:
    main:                Main.hs
    source-dirs:         test
    dependencies:
      - base
      - cryptonite
      - memory
      - tasty
      - tasty-discover
      - tasty-hunit
      - tasty-quickcheck
      - QuickCheck
      - bulletproofs

benchmarks:
  bulletproofs-benchmarks:
    source-dirs: bench
    main: Main.hs
    dependencies:
      - bulletproofs
      - criterion >= 1.5.1.0
      - QuickCheck
      - tasty
      - tasty-quickcheck
      - tasty-hunit

executables:
  bulletproofs-example:
    main: Main.hs
    source-dirs: example
    ghc-options:
      - -O2
    dependencies:
      - bulletproofs
